swagger: "2.0"
info:
  version: "0.0.4"
  title: FP Order service
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/xml
paths:
  /tea/orders:
    # binds a127 app logic to a route
    x-swagger-router-controller: orders
    get:
      description: List of tea types to order
      # used as the method name of the controller
      operationId: listOrders
      parameters:
        - name: spotId
          in: query
          description: Tea spot to filter out
          required: false
          type: string
        - name: startTime
          in: query
          description: Start time of orders updates
          required: false
          type: string
        - name: endTime
          in: query
          description: End time of orders updates
          required: false
          type: string
        - name: page
          in: query
          description: Page to iterate, 1 is default
          required: false
          type: number
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
                $ref: "#/definitions/TeaOrder"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /cinema/stats:
    x-swagger-router-controller: orders
    get:
      description: List of cinema and their nimber of guestes
      # used as the method name of the controller
      operationId: cinema
      parameters:
        - name: date
          in: query
          description: Date to get the stats
          required: false
          type: string
        - name: cinema_name
          in: query
          description: Names of cinema
          required: false
          type: string
        - name: visitors
          in: query
          description: Number of visitors
          required: false
          type: number
      responses:
        "200":
          description: Success
          schema:
              type: string
              $ref: "#/definitions/Stats"


        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  TeaOrder:
    required:
      - id
    properties:
      id:
        type: string
      takeOffId:
        type: number
      teaType:
        type: string
      time:
        type: string
      status:
        description: queue | ready | taken
        type: string

  Stats:
    xml:
      name: cinema
    properties:
      cinema_name:
        type: string
        xml:
          attribute: true
      date:
        type: string
        xml:
          attribute: true
      visitors:
        type: number
        xml:
          attribute: true


  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
